name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出后端代码
        uses: actions/checkout@v4

      - name: 检出前端代码
        uses: actions/checkout@v4
        with:
          repository: dnslin/code-share
          path: frontend

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 构建前端
        working-directory: frontend
        run: |
          pnpm install
          pnpm build

      - name: 准备构建文件
        run: |
          # 创建构建目录
          mkdir -p build
          # 复制后端文件
          cp -r app requirements.txt build/
          # 复制前端构建文件
          cp -r frontend/dist build/frontend-dist
          # 创建 Caddyfile
          echo ":80 {
            handle /api/* {
              reverse_proxy localhost:8000
            }
            handle /* {
              root * /srv
              try_files {path} /index.html
              file_server
            }
          }" > build/Caddyfile

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: build
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/code-share:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/code-share:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
